# 异常

异常一般用在不确定是否出错的代码块中

### 常见异常

* ZeroDivisionError：除0异常
* NameError：变量异常
* SyntaxError：语法错误
* TypeError：类型错误
* IndexError：索引错误

异常会让程序中止退出，若人为处理异常，不会产生错误和崩溃

### 人为处理异常的方法

先执行try中的语句，参数为2时没有异常就执行else中的语句；参数为0时有异常就执行except中的语句

```python
def try_except(num):
    try:
        print(2/num)
    except ZeroDivisionError as e:
        print("程序错误",e)
    else:
        print('程序正常执行')

try_except(2)
print("\n")
try_except(0)


#1.0
#程序正常执行

#程序错误 division by zero
```

这样的写法只能捕获该类异常，若出现其他异常程序依然报错，有两种方法解决

#### 多个except语句

```python
def try_except(num):
    try:
        print(2/num)
    except ZeroDivisionError as e:
        print("程序错误",e)
    except TypeError as e:
        print("程序错误",e)
    else:
        print('程序正常执行')

try_except(2)
print("\n")
try_except(0)
try_except('a')


#1.0
#程序正常执行

#程序错误 division by zero
#程序错误 unsupported operand type(s) for /: 'int' and 'str'
```

当程序有多个异常时会按照顺序捕获异常，一旦捕获就会退出，后面的异常不会被捕获

#### Exception

Exception是所有异常的父类，使用Exception或者什么都不写，会捕获所有异常

```python
def try_except(num):
    try:
        print(2/num)
    except ZeroDivisionError as e:
        print("程序错误",e)
    except Exception as e:
    	print("程序错误",e)	
    else:
        print('程序正常执行')

try_except(2)
print("\n")
try_except(0)
try_except('a')

#1.0
#程序正常执行

#程序错误 division by zero
#程序错误 unsupported operand type(s) for /: 'int' and 'str'
```

### finally

无论程序如何运行，finally中的语句一定会执行，哪怕之前出现了return，break

```python
while True:
    try:
        n=input('>')
        if n=='q':
            break
        print('{:.2f}'.format(2/float(n)))
    except Exception as e:
        print('输入错误！',e)
    else:
        print('正常运行')
    finally:
        print('怎么哪都有我？')
 

#>3
#0.67
#正常运行
#怎么哪都有我？

#>d
#输入错误！ could not convert string to float: 'd'
#怎么哪都有我？

#>q
#怎么哪都有我？
```



## 自定义异常

用户可以自定义异常，由raise抛出，该代码块中raise后的语句不会执行。```raise```会将异常打印出来，```raise 自定义异常```只会抛出该异常，不会打印

```python
# 定义从Exception或各类Error继承的子类
class Whatevererror(Exception):
    pass

while True:
    try:
        n=input('>')
        if n=='q':
            break
        raise Whatevererror('不管你输啥，都是错') # 抛出异常
        print('不会执行')
    except Whatevererror as e:    # 捕获异常
        print('hhh',e)
        raise 
        
#>w
#hhh 不管你输啥，都是错
#---------------------------------------------------------------------------
#Whatevererror                             Traceback (most recent call last)
#<ipython-input-12-c1f10858b4d4> in <module>
#      9         if n=='q':
#     10             break
#---> 11         raise Whatevererror('不管你输啥，都是错') # 引起异常
#     12         print('不会执行')
#     13     except Whatevererror as e:  # 捕获异常

#Whatevererror: 不管你输啥，都是错
```

## 警告

提醒用户，但不终止程序

```python
import warnings
def months(month):
    if not 1<=month<=12:
        msg='Month cannot be greater than 12 or less than 1'
        warnings.warn(msg)
        print('程序正常执行')

months(13)

#程序正常执行
#d:\python_3.7.0\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Month #cannot be greater than 12 or less than 1
  
```







